"""add devices table

Revision ID: 8bcf63c8173a
Revises: 8e402244e8ed
Create Date: 2026-09-26 22:27:20.258154

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8bcf63c8173a"
down_revision: Union[str, Sequence[str], None] = "8e402244e8ed"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "devices",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dev_eui", sa.String(length=16), nullable=False),
        sa.Column("app_id", sa.UUID(), nullable=False),
        sa.Column("join_eui", sa.String(length=16), nullable=False),
        sa.Column("app_key", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["app_id"], ["application.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_devices_dev_eui"),
        "devices",
        ["dev_eui"],
        unique=True,
    )
    op.create_index(
        op.f("ix_devices_app_id"),
        "devices",
        ["app_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_devices_dev_eui"), table_name="devices")
    op.drop_index(op.f("ix_devices_app_id"), table_name="devices")
    op.drop_table("devices")
    # ### end Alembic commands ###
