"""add device_routes table

Revision ID: 8e402244e8ed
Revises: 0c14cfa628c3
Create Date: 2026-09-16 23:39:05.556931

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8e402244e8ed"
down_revision: Union[str, Sequence[str], None] = "0c14cfa628c3"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "device_routes",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("dev_eui", sa.String(length=16), nullable=False),
        sa.Column("app_id", sa.UUID(), nullable=False),
        sa.Column("agent_endpoint", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["app_id"], ["application.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_device_routes_dev_eui"),
        "device_routes",
        ["dev_eui"],
        unique=True,
    )
    op.create_index(
        op.f("ix_device_routes_app_id"),
        "device_routes",
        ["app_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_device_routes_dev_eui"), table_name="device_routes")
    op.drop_index(op.f("ix_device_routes_app_id"), table_name="device_routes")
    op.drop_table("device_routes")
    # ### end Alembic commands ###
